### PR TITLE
Chosen select component

### PR DESCRIPTION
**Pull request by JPLachance**
Since react-chosen was incompatible with React 15 and was difficult to use in Typescript (no definition file and naming clash with the react Chosen definition file), I implemented my own version of that Component.

### CODE REVIEW

File: docs/Index.tsx [hunk 1]
```diff
@@ -352,6 +353,32 @@ class App extends React.Component<any, any> {
...
+              <option value='United States'>United States</option>
+            </ChosenSelect>
+          </div>
+        </div>
+        <div className='form-group'>
+          <label className='form-control-label'>
+            Chosen multi select
+          </label>
+          <div className='form-control'>
+            <ChosenSelect placeholderTextSingle='Choose a country' defaultValue={['Canada']} multiple width='400px'
```
Comment (wfortin) [inline docs/Index.tsx]: This is because you can't use the reserved word placeholder, right ?

Comment (JPLachance) [inline docs/Index.tsx]: No, it's simply the name of the Chosen parameter.

File: docs/Index.tsx [hunk 2]
```diff
@@ -10,6 +10,7 @@ import { createStore } from 'redux';
 import { connect, Provider } from 'react-redux';
 
 import { ReduxUtils } from '../src/utils/ReduxUtils';
+import { ChosenSelect } from '../src/components/ChosenSelect.tsx';
 import { Popover } from '../src/components/Popover';
 import { Svg } from '../src/components/Svg.tsx';
```
Comment (wfortin) [inline docs/Index.tsx]: Don't add the .tsx suffix, it's unnecessary.

Comment (JPLachance) [inline docs/Index.tsx]: Was auto-imported by WebStorm, I'll remove it!

Comment (wfortin) [inline docs/Index.tsx]: Maybe there a setting to omit the extension.

File: src/components/ChosenSelect.tsx [hunk 3]
```diff
@@ -0,0 +1,91 @@
+///<reference types="chosen" /> Required since typings name (@types/chosen) is not the same as the npm package name (chosen-js)
+
+import * as React from 'react';
+import * as $ from 'jquery';
+import * as _ from 'underscore';
+
+import 'chosen-js'; // Clean way to make Webpack import something that is not a module
```
Comment (GermainBergeron) [inline src/components/ChosenSelect.tsx]: TIL

File: src/components/ChosenSelect.tsx [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+
+export interface IChosenSelectProps extends React.HTMLProps<ChosenSelect> {
```
Comment (GermainBergeron) [inline src/components/ChosenSelect.tsx]: I don't like the ISomething for the interfaces.

File: src/components/ChosenSelect.tsx [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+  onChosenChange?: (event: JQueryEventObject, args: Chosen.SelectedData) => void;
+  placeholderTextMultiple?: string; // @default: "Select Some Options"
+  placeholderTextSingle?: string; // @default: "Select an Option"
+  searchContains?: boolean; // @default: false
+  singleBackstrokeDelete?: boolean; // @default: true
+  width?: string; // @default: the width of the select chosen is replacing
+}
+
+/**
+ * List of props that where passed to the <ChosenSelect> component but that should not be passed to the <select> element to avoid warnings.
```
Comment (GermainBergeron) [inline src/components/ChosenSelect.tsx]: List of props that **were** ...

File: src/components/ChosenSelect.tsx [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+   * HACK: Since we cannot overrdide onChange method signature (provided by React.HTMLProps<HTMLSelectElement>), since onChange is
+   * required by React when a value has been specified (component becomes "controlled") and because chosen does not trigger the change
+   * event on the <select> and foces us to use jQuery, we added a onChosenChange prop and faked the onChange prop.
+   * @returns {JSX.Element | null}
+   */
+  render() {
+    // Omit ChosenSelect props to avoid warnings.
+    let selectProps = _.extend({}, _.omit(this.props, chosenSelectPropsToOmit));
+    return (
+      <select {...selectProps} ref='select' onChange={_.noop}>
```
Comment (GermainBergeron) [inline src/components/ChosenSelect.tsx]: in UA instead of doing `ref='select'` I did this:
```
private select: JQuery;
...
<select 
  ref={(el: HTMLSelectElement) => this.select = $(el)}>
```

This way, this.select is always the jQuery element, and I don't need to use `this.refs`. What do you think?

File: src/components/Svg.tsx [hunk 7]
```diff
@@ -14,30 +16,38 @@ const setSvgClass = (svgString: string, svgClass: string): string => {
 
 /**
  * Pass the required svgName to get your svg.
- * Use className to pass the "icon" class and any sizing class.
- * Use svgClass to pass the svg fill class.
+ * Use svgClass to pass the svg fill class (and the icon class if you didn't pass is as className).
  */
-export interface ISvgProps extends React.ClassAttributes<Svg> {
-  className?: string;
+export interface ISvgProps extends React.HTMLProps<Svg> {
```
Comment (GermainBergeron) [inline src/components/Svg.tsx]: I'll say it again: I don't like the `I` in the interfaces

File: src/components/Svg.tsx [hunk 8]
```diff
@@ -14,30 +16,38 @@ const setSvgClass = (svgString: string, svgClass: string): string => {
...
   svgClass?: string;
   svgName: string;
 }
 
+/**
+ * List of props that where passed to the <Svg> component but that should not be passed to the <span> element to avoid warnings.
```
Comment (GermainBergeron) [inline src/components/Svg.tsx]: were

File: tests/components/Chosen.spec.tsx [hunk 9]
```diff
@@ -0,0 +1,79 @@
+import { shallow, mount, ReactWrapper } from 'enzyme';
+import * as $ from 'jquery';
+import { IChosenSelectProps, ChosenSelect } from '../../src/components/ChosenSelect';
+
+// Until Webpack provided plugins works with TS 2.0
+/* tslint:disable:no-unused-variable */
+import * as React from 'react';
```
Comment (GermainBergeron) [inline tests/components/Chosen.spec.tsx]: Can you use `import 'react';` instead?

File: tests/components/Chosen.spec.tsx [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+  it('should render without error', () => {
+    expect(() => {
+      shallow(
+        <ChosenSelect {...chosenSelectProps}>
+          <option value='1'>Option 1</option>
+          <option value='2'>Option 2</option>
+          <option value='3'>Option 3</option>
+        </ChosenSelect>
+      );
+    }).not.toThrow();
```
Comment (GermainBergeron) [inline tests/components/Chosen.spec.tsx]: To keep it concise you can do 
```
expect(() => shallow(
  <ChosenSelect {...chosenSelectProps}>
    <option value='1'>Option 1</option>
    <option value='2'>Option 2</option>
    <option value='3'>Option 3</option>
  </ChosenSelect>
)).not.toThrow();
```

File: src/components/ChosenSelect.tsx (hunk 6 above)
Comment (JPLachance) [inline src/components/ChosenSelect.tsx]: Sold!

File: tests/components/Chosen.spec.tsx (hunk 10 above)
Comment (JPLachance) [inline tests/components/Chosen.spec.tsx]: Done!

File: tests/components/Chosen.spec.tsx (hunk 9 above)
Comment (JPLachance) [inline tests/components/Chosen.spec.tsx]: error TS2686: Identifier 'React' must be imported from a module
